import React from 'react';
const S = { blue:'#1D4ED8', navy:'#0C1A2E', bg:'#F8FAFF', card:'#FFFFFF', border:'#E2EBF6', muted:'#3B5998', hint:'#94a3b8', lightBlue:'#EFF6FF' };
const Section = ({ title, children }) => (
  <div style={{ marginBottom:32 }}>
    <h2 style={{ fontSize:16, fontWeight:700, color:S.navy, letterSpacing:'-0.01em', marginBottom:12, paddingBottom:8, borderBottom:'0.5px solid '+S.border }}>{title}</h2>
    <div style={{ fontSize:14, color:S.muted, lineHeight:1.8 }}>{children}</div>
  </div>
);
export default function Terms({ onBack }) {
  return (
    <div style={{ fontFamily:"'Satoshi',-apple-system,sans-serif", background:S.bg, minHeight:'100vh', padding:'40px 24px' }}>
      <div style={{ maxWidth:720, margin:'0 auto' }}>
        <button onClick={onBack} style={{ fontSize:13, color:S.blue, background:'none', border:'none', cursor:'pointer', marginBottom:32, fontWeight:600 }}>← Back</button>
        <div style={{ marginBottom:32 }}>
          <div style={{ fontSize:11, fontWeight:600, color:S.blue, letterSpacing:'0.08em', textTransform:'uppercase', marginBottom:8 }}>Legal</div>
          <h1 style={{ fontSize:28, fontWeight:700, color:S.navy, letterSpacing:'-0.02em', margin:'0 0 8px' }}>Terms of Service</h1>
          <p style={{ fontSize:13, color:S.hint, margin:0 }}>Last updated: June 2026 · By using PsycheFlow, you agree to these terms.</p>
        </div>
        <div style={{ background:S.card, borderRadius:12, padding:32, border:'0.5px solid '+S.border, boxShadow:'0 1px 4px rgba(29,78,216,0.06)' }}>
          <Section title="1. Acceptance of Terms">
            <p>By creating an account on PsycheFlow, you agree to these Terms of Service and our Privacy Policy. If you do not agree, do not use the platform.</p>
          </Section>
          <Section title="2. What PsycheFlow Is">
            <p>PsycheFlow is a digital mental health support platform that provides AI-powered psychological screening, therapy tools, and clinician support features. It is designed as a supportive tool — not a replacement for professional mental health care.</p>
            <p>PsycheFlow does not provide medical diagnosis. Assessment results are screening indicators generated by machine learning models trained on validated instruments. They are not clinical diagnoses and should not be treated as such.</p>
          </Section>
          <Section title="3. Eligibility">
            <p>You must be at least 18 years of age to use PsycheFlow. By registering, you confirm that you are 18 or older.</p>
            <p>Psychologists registering on PsycheFlow must hold valid credentials from the Rehabilitation Council of India (RCI) or equivalent. PsycheFlow reserves the right to verify credentials and suspend accounts that cannot be verified.</p>
          </Section>
          <Section title="4. Your Account">
            <p>You are responsible for maintaining the confidentiality of your account credentials. You are responsible for all activity that occurs under your account.</p>
            <p>You must provide accurate information when registering. Impersonation of a healthcare professional is a violation of these terms and may be reported to relevant authorities.</p>
          </Section>
          <Section title="5. Appropriate Use">
            <p>You agree not to use PsycheFlow to:</p>
            <p>• Provide false information about yourself or your credentials.</p>
            <p>• Attempt to access another user's data.</p>
            <p>• Use the platform in any way that could harm other users.</p>
            <p>• Reverse engineer, scrape, or extract data from the platform.</p>
            <p>• Use the AI features to generate harmful, misleading, or dangerous content.</p>
          </Section>
          <Section title="6. Crisis Situations">
            <p>If you are experiencing a mental health crisis, please contact emergency services or a crisis helpline immediately:</p>
            <p>• iCall: 9152987821</p>
            <p>• Vandrevala Foundation: 1860-2662-345</p>
            <p>• NIMHANS: 080-46110007</p>
            <p>PsycheFlow's automated crisis detection is a supplementary tool and is not a substitute for emergency services.</p>
          </Section>
          <Section title="7. Intellectual Property">
            <p>All content, models, code, and design elements of PsycheFlow are the intellectual property of PsycheFlow. You may not reproduce, distribute, or create derivative works without written permission.</p>
            <p>Your personal data and clinical records remain your property. See our Privacy Policy for details on data ownership and deletion rights.</p>
          </Section>
          <Section title="8. Limitation of Liability">
            <p>PsycheFlow is provided as-is. We make no warranties regarding the accuracy, completeness, or fitness of AI-generated assessments for any clinical purpose.</p>
            <p>To the maximum extent permitted by law, PsycheFlow shall not be liable for any indirect, incidental, or consequential damages arising from use of the platform.</p>
          </Section>
          <Section title="9. Changes to Terms">
            <p>We may update these terms from time to time. We will notify registered users by email when significant changes are made. Continued use of the platform after notification constitutes acceptance of the updated terms.</p>
          </Section>
          <Section title="10. Governing Law">
            <p>These terms are governed by the laws of India. Any disputes shall be subject to the jurisdiction of courts in Ghaziabad, Uttar Pradesh, India.</p>
          </Section>
          <Section title="11. Contact">
            <p>For questions about these terms: dpksaxena21@gmail.com</p>
          </Section>
        </div>
      </div>
    </div>
  );
}
